export const APP_URL = "https://app.writidian.com";

export const SITE = {
  name: "Writidian",
  tagline: "A space for intentional writing.",
  description:
    "Writidian is a writing sanctuary for people who want to think and write for themselves. Soundscapes, daily prompts, and a built-in editor. No AI.",
};

export const COPY = {
  heroHeadline: "Write like the craft still matters.",
  heroSupport:
    "A quiet space that raises your odds of finishing what you started.",
  problemWords:
    "Phones, tabs, and digital noise compete with focus. The place you sit down in should help you finish, not work against you.",
  soundscapesTitle: "Soundscapes that match your story",
  soundscapesBody:
    "Pair the scene on the page with the world in your ears. Writing a forest chapter? Step into forest sound. Each soundscape is built to hold the mood while you write.",
  binaurals:
    "Binaurals for focused headspace. Alpha for relaxed focus, Beta for alertness, Gamma for peak attention, Theta for creativity, Delta for deep calm.",
  binauralsTip: "Use headphones for best effect.",
  promptTitle: "A prompt waiting every morning",
  promptBody:
    "A new prompt every day from a large collection. Sometimes a scene starter you continue. Built to provoke thinking and get you writing immediately.",
  samplePromptLabel: "Nostalgia",
  samplePrompt:
    "There is a song you refuse to listen to anymore because it transports you to a time you can't get back. What time is that?",
  editorTitle: "The editor lives here",
  editorBody:
    "Writing happens inside Writidian itself. No bouncing between tools. Open a prompt, start a draft, stay in the flow.",
  streakTitle: "Momentum that stays with you",
  streakBody:
    "Build a writing streak you can feel. Each day you show up, the flame grows. Miss a day and it resets. Simple pressure that keeps you returning to the page.",
  analyticsTitle: "See your writing rhythm",
  analyticsBody:
    "Track sanctuary hours, words flowed, and the shape of your week. A quiet mirror of your practice, not a leaderboard.",
  stanceTitle: "Built against the grain",
  stanceBody:
    "AI has thinned the art of writing and the wellbeing that comes with doing hard creative work yourself. Writidian takes the other path. No generators. No rewrite buttons. A space that asks you to think.",
  platformNote:
    "Writidian is a web app today. A mobile app is in the pipeline.",
  finalCta: "Start writing for free.",
  finalSupport: "Sign up and step into your sanctuary.",
};

export const GENRES = [
  "Romance",
  "Horror",
  "Sci-fi",
  "Fantasy",
  "Literary",
  "Journaling",
  "Mystery",
  "Poetry",
] as const;

/** Social-style notification clutter for the sanctuary reveal */
export const SOCIAL_CLUTTER = [
  {
    id: "s1",
    brand: "instagram" as const,
    platform: "Instagram",
    title: "maya · liked your photo",
    body: "and 14 others · 2m",
    accent: "#E1306C",
    x: 10,
    y: 12,
    mx: 8,
    my: 10,
    ox: -48,
    oy: -38,
    rot: -16,
    mobile: true,
  },
  {
    id: "s2",
    brand: "x" as const,
    platform: "X",
    title: "Trending in your area",
    body: "Hot take thread you do not need",
    accent: "#000000",
    x: 78,
    y: 10,
    mx: 78,
    my: 12,
    ox: 52,
    oy: -42,
    rot: 14,
    mobile: true,
  },
  {
    id: "s3",
    brand: "discord" as const,
    platform: "Discord",
    title: "#general · writers-den",
    body: "12 new mentions waiting for you",
    accent: "#5865F2",
    x: 16,
    y: 36,
    mx: 14,
    my: 32,
    ox: -56,
    oy: 8,
    rot: -10,
    mobile: true,
  },
  {
    id: "s4",
    brand: "tiktok" as const,
    platform: "TikTok",
    title: "For You",
    body: "Watch this before you write",
    accent: "#FE2C55",
    x: 84,
    y: 34,
    mx: 82,
    my: 38,
    ox: 50,
    oy: 6,
    rot: 18,
    mobile: false,
  },
  {
    id: "s5",
    brand: "pinterest" as const,
    platform: "Pinterest",
    title: "47 new ideas for you",
    body: "Writing desks & quiet corners",
    accent: "#E60023",
    x: 48,
    y: 16,
    mx: 48,
    my: 18,
    ox: -8,
    oy: -52,
    rot: -20,
    mobile: true,
  },
  {
    id: "s6",
    brand: "slack" as const,
    platform: "Slack",
    title: "design-team",
    body: "Another ping. Another tab.",
    accent: "#4A154B",
    x: 62,
    y: 58,
    mx: 70,
    my: 58,
    ox: 44,
    oy: 38,
    rot: 12,
    mobile: true,
  },
  {
    id: "s7",
    brand: "whatsapp" as const,
    platform: "WhatsApp",
    title: "Jordan",
    body: "hey u free rn???",
    accent: "#25D366",
    x: 12,
    y: 68,
    mx: 18,
    my: 72,
    ox: -50,
    oy: 44,
    rot: -14,
    mobile: true,
  },
  {
    id: "s8",
    brand: "calendar" as const,
    platform: "Calendar",
    title: "Standup",
    body: "Starts in 5 minutes",
    accent: "#E74C3C",
    x: 86,
    y: 70,
    mx: 82,
    my: 78,
    ox: 48,
    oy: 40,
    rot: 16,
    mobile: false,
  },
  {
    id: "s9",
    brand: "chatgpt" as const,
    platform: "ChatGPT",
    title: "Rewrite this?",
    body: "Generate a better paragraph",
    accent: "#10A37F",
    x: 34,
    y: 52,
    mx: 36,
    my: 52,
    ox: -42,
    oy: 22,
    rot: -12,
    mobile: false,
  },
  {
    id: "s10",
    brand: "youtube" as const,
    platform: "YouTube",
    title: "Suggested for you",
    body: "Infinite scroll is calling",
    accent: "#FF0000",
    x: 70,
    y: 44,
    mx: 62,
    my: 48,
    ox: 46,
    oy: -12,
    rot: 10,
    mobile: false,
  },
] as const;

export const SOUNDSCAPE_SCENES = [
  {
    id: "forest",
    title: "Forest night",
    line: "Crickets in the dark. Soft wind through the pines. Your scene outside the window.",
    image: "/images/soundscape-forest.png",
  },
  {
    id: "coast",
    title: "Coast",
    line: "Slow tide against the shore. Salt air. The page keeps rhythm with the waves.",
    image: "/images/soundscape-coast.png",
  },
  {
    id: "night",
    title: "Night desk",
    line: "One lamp. Soft room hush. The rest of the world on mute.",
    image: "/images/soundscape-night.png",
  },
] as const;
